theme: jekyll-theme-cayman
title: [Sequence to Multi-Sequence Learning via Probabilistic Chain Rule]
description: [A general methods to learn one-to-many sequence transduction problems, 
which could be widely used in multi-speaker separation, recognition and other tasks.]
