theme: jekyll-theme-cayman
title: Sequence to Multi-Sequence Learning via Probabilistic Chain Rule
description: A general method to learn one-to-many sequence transduction problems, which could be widely used in multi-speaker separation, recognition and other tasks.

subtitle: Seq2Mseq
name: Seq2Mseq 
